### ISSUE TITLE
Some enhancements?

### ISSUE THREAD

**Issue by ScottishFold007** [tfernd/sd-fused#2]
Hello, you have a great library! I've tried it many times and the results are awesome! But the shortcoming is that it lacks the correction of face details and the restoration of image details. Can you consider adding post-processing algorithms such as RealESRGAN, ESRGAN, CodeFormer, GFPGAN, etc.? Looking forward to your improvement, thanks!

**Comment by tfernd** [comment]
Those are good points. I'll add it to my TODO list.

**Comment by ScottishFold007** [comment]
Great! don't forget CLIP guide～



---Original---
From: "Thales ***@***.***&gt;
Date: Fri, Oct 21, 2022 00:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tfernd/sd-fused] Some enhancements? (Issue #2)




 
Those are good points. I'll add it to my TODO list.
